### PR TITLE
Adapt to more recent coq versions (>= 8.14)

### PR DESCRIPTION
**Pull request by olaure01**
The proposed modified files should compile with Coq 8.14, 8.15 and 8.16.

### CODE REVIEW

**Comment by olaure01** [comment]
Ping @Matafou 
Works with coq8.16.1 as well.

**Comment by Matafou** [comment]
Thanks for the ping. I merge!

**Comment by Matafou** [comment]
I guess we should add a credit file now :-) and maybe a license too.

**Comment by olaure01** [comment]
> I guess we should add a credit file now :-) and maybe a license too.

Up to you: my main goal is to ensure sources can be compiled, not to interfere with the management of projects .

**Pull request merged**
